module.exports = {
  apps: [
    {
      name: "e2e-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "login-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/login.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "stamping-peranan-ejen-duti-setem-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/stamping-peranan-ejen-duti-setem.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "stamping-peranan-ejen-firma-guaman-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/stamping-peranan-ejen-firma-guaman.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-ejen-duti-setem-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-ejen-duti-setem.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "stamping-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/stamping.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "login2-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/login2.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-penalty-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-penalty.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-combine-penalti-without-penalty-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-combine-penalti-without-penalty.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-combine-penalti-without-penalty-worker2-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-combine-penalti-without-penalty-worker2.spec.ts --output=test-results-worker2 --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-forever",
      script: "cmd.exe",
      args: '/c npx playwright test tests/SRN-PUMP-LATEST.spec.ts',
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-peranan-forever",
      script: "cmd.exe",
      args: '/c npx playwright test tests/SRN-pump-peranan.spec.ts',
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-dev-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN_dev.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    }
  ],
};
