module.exports = {
  apps: [
    {
      name: "e2e-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "login-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/login.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "stamping-peranan-ejen-duti-setem-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/stamping-peranan-ejen-duti-setem.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "stamping-peranan-ejen-firma-guaman-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/stamping-peranan-ejen-firma-guaman.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-ejen-duti-setem-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-ejen-duti-setem.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "stamping-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/stamping.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "login2-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/login2.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-penalty-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-penalty.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-combine-penalti-without-penalty-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-combine-penalti-without-penalty.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "e2e-combine-penalti-without-penalty-worker2-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/e2e-combine-penalti-without-penalty-worker2.spec.ts --output=test-results-worker2 --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-peranan-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-pump-peranan.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-dev-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN_dev.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN.spec.ts --project=chromium --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
      env: {
        PWDEBUG_PORT: "9222"
      }
    },
    {
      name: "srn-pump-latest-dikecualiakn-headless-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-headless-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-staff-feds-headless-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-STAFF-FEDS.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-optimized-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-OPTIMIZED.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-dev-new-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-DEV-NEW.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-normal-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-NORMAL.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "generate-pdf-forever",
      script: "cmd.exe",
      args: "/c node generate-pdf.js",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-worker2.spec.ts --project=chromium --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-penalty-only-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-PENALTY-ONLY.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-normal-syarikat-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-NORMAL-SYARIKAT.spec.ts",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-normal-syarikat-worker2-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-NORMAL-SYARIKAT-worker2.spec.ts --output=test-results-worker2 --reporter=list",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-worker2-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-worker2.spec.ts --output=test-results-worker2-dikecualiakn --reporter=list",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-worker3-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-worker3.spec.ts --output=test-results-worker3-dikecualiakn --reporter=list",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-worker2-forever",
      script: "npm",
      args: "run srn-pump-latest-dikecualiakn-missing-phone-worker2:one",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-staff-feds-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-STAFF-FEDS.spec.ts --project=msedge --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-fg-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-FG.spec.ts --project=chromium --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "srn-pump-latest-dikecualiakn-missing-phone-individu-forever",
      script: "cmd.exe",
      args: "/c npx playwright test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-INDIVIDU.spec.ts --project=chromium --reporter=list",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "quad-worker1-dikecualiakn",
      script: "node_modules/@playwright/test/cli.js",
      args: "test tests/SRN-PUMP-LATEST-DIKECUALIAKN.spec.ts --project=chromium --reporter=list --output=test-results-quad-worker1",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "quad-worker2-fg",
      script: "node_modules/@playwright/test/cli.js",
      args: "test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-FG.spec.ts --project=chromium --reporter=list --output=test-results-quad-worker2",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "quad-worker3-individu",
      script: "node_modules/@playwright/test/cli.js",
      args: "test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-INDIVIDU.spec.ts --project=chromium --reporter=list --output=test-results-quad-worker3",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
    {
      name: "quad-worker4-staff-feds",
      script: "node_modules/@playwright/test/cli.js",
      args: "test tests/SRN-PUMP-LATEST-DIKECUALIAKN-MISSING-PHONE-STAFF-FEDS.spec.ts --project=chromium --reporter=list --output=test-results-quad-worker4",
      cwd: "C:/GitProjects/SRN-data-pump",
      autorestart: true,
      restart_delay: 10000,
      time: true,
    },
  ],
};
